=== pasamio/pasamioprojects/jinstallmanager/trunk/resources/component-install.dtd
<!ELEMENT install ((name, creationDate, author, authorEmail, authorUrl, copyright, license, version, description, installfile, uninstallfile, install, uninstall, files*, languages*, media*, administration, params?, downloadsource*) | (sql | queries))+>
<!ATTLIST install
	type NMTOKEN #FIXED "component"
	version CDATA #IMPLIED
>
<!ELEMENT name (#PCDATA)>
<!ELEMENT creationDate (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT authorEmail (#PCDATA)>
<!ELEMENT authorUrl (#PCDATA)>
<!ELEMENT copyright (#PCDATA)>
<!ELEMENT license (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ATTLIST version
	id CDATA #REQUIRED
>
<!ELEMENT description (#PCDATA)>
<!ELEMENT administration (menu | submenu | files | languages | media)*>
<!ELEMENT files (filename | folder)*>
<!ATTLIST files
	folder CDATA #IMPLIED
>
<!ELEMENT filename (#PCDATA)>
<!ELEMENT folder (#PCDATA)>
<!ELEMENT languages (language)+>
<!ATTLIST languages
	folder CDATA #IMPLIED
>
<!ELEMENT language (#PCDATA)>
<!ATTLIST language
	tag CDATA #REQUIRED
>
<!ELEMENT media (filename)*>
<!ATTLIST media
	destination CDATA #IMPLIED
	folder CDATA #IMPLIED
>
<!ELEMENT menu (#PCDATA)>
<!ATTLIST menu
	act NMTOKEN #IMPLIED
	task NMTOKEN #IMPLIED
	controller NMTOKEN #IMPLIED
	view NMTOKEN #IMPLIED
	layout NMTOKEN #IMPLIED
	sub NMTOKEN #IMPLIED
	img CDATA #IMPLIED
	link CDATA #IMPLIED
>
<!ELEMENT submenu (menu)+>
<!ELEMENT uninstall (sql | queries)>
<!ELEMENT sql (file)*>
<!ELEMENT queries (query)*>
<!ELEMENT file (#PCDATA)>
<!ATTLIST file
	charset NMTOKEN #FIXED "utf8"
	driver NMTOKEN #REQUIRED
>
<!ELEMENT query (#PCDATA)>
<!ATTLIST query
	id NMTOKEN #IMPLIED
>
<!ELEMENT installfile (#PCDATA)>
<!ELEMENT uninstallfile (#PCDATA)>
<!ELEMENT params (param)*>
<!ATTLIST param
	addParameterDir CDATA #IMPLIED
>
<!ELEMENT param (#PCDATA | option)*>
<!ATTLIST param
	name NMTOKEN #REQUIRED
	type NMTOKEN #REQUIRED
	label CDATA #REQUIRED
	size NMTOKEN #IMPLIED
	id NMTOKEN #IMPLIED
	class NMTOKEN #IMPLIED
	default CDATA #IMPLIED
	description CDATA #IMPLIED
	section NMTOKEN #IMPLIED
	scope NMTOKEN #IMPLIED
	directory CDATA #IMPLIED
	filter CDATA #IMPLIED
	exclude CDATA #IMPLIED
	stripext CDATA #IMPLIED
	hide_none NMTOKEN #IMPLIED
	hide_default NMTOKEN #IMPLIED
	client NMTOKEN #IMPLIED
	menu_type NMTOKEN #IMPLIED
	state NMTOKEN #IMPLIED
	rows NMTOKEN #IMPLIED
	cols NMTOKEN #IMPLIED
>
<!ELEMENT option (#PCDATA)>
<!ATTLIST option
	value CDATA #IMPLIED
>
<!ELEMENT downloadsource (#PCDATA)>

=== pasamio/pasamioprojects/jlibman/trunk/jlibman.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE install SYSTEM "http://dev.joomla.org/xml/1.5/component-install.dtd">
<install type="component" version="1.5.0">
 <name>JLibMan</name>
 <!-- The following elements are optional and free of formatting conttraints -->
 <creationDate>21-Sep-2007</creationDate>
 <author>Sam Moffatt</author>
 <authorEmail>S.Moffatt@toowoomba.qld.gov.au</authorEmail>
 <authorUrl>http://www.toowoomba.qld.gov.au</authorUrl>
 <copyright>Copyright (c) 2007 Toowoomba City Council/Sam Moffatt</copyright>
 <license>GNU GPL</license>
 <!--  The version string is recorded in the components table -->
 <version>0.1</version>
 <!-- The description is optional and defaults to the name -->
 <description>This component is designed to allow custom library installation</description>
 <administration>
  <!-- Administration Menu Section -->
  <menu>JLibMan</menu>
  
  <!-- Administration Main File Copy Section -->
  <files folder="admin">
   <filename>index.html</filename>
   <filename>admin.jlibman.php</filename>
  </files>  
 </administration>
</install>

=== pasamio/pasamioprojects/jdevtools/trunk/jdevtools.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE install SYSTEM "http://dev.joomla.org/xml/1.5/component-install.dtd">
<install type="component" version="1.5.0">
	<name>JDevTools</name>
	<!-- The following elements are optional and free of formatting conttraints -->
	<creationDate>21-Sep-2007</creationDate>
	<author>Sam Moffatt</author>
	<authorEmail>S.Moffatt@toowoomba.qld.gov.au</authorEmail>
	<authorUrl>http://www.toowoomba.qld.gov.au</authorUrl>
	<copyright>Copyright (c) 2007 Toowoomba City Council/Sam Moffatt</copyright>
	<license>GNU GPL</license>
	<!--  The version string is recorded in the components table -->
	<version>0.1</version>
 	<!-- The description is optional and defaults to the name -->
	<description>This component is designed to help a developer interacting with Joomla! Code</description>

	<!-- Site Main File Copy Section -->
	<!-- Note the folder attribute: This attribute describes the folder
	      to copy FROM in the package to install therefore files copied
	      in this section are copied from /site/ in the package -->
	<files folder="site">
		<filename>index.html</filename>
		<filename>jdevtools.php</filename>
		<filename>controller.php</filename>
		<filename>views/index.html</filename>
		<filename>views/jdevtools/index.html</filename>
		<filename>views/jdevtools/view.html.php</filename>
		<filename>views/jdevtools/tmpl/index.html</filename>
		<filename>views/jdevtools/tmpl/default.php</filename>
		<filename>models/jdevtools.php</filename>
	</files>
	<install>
		<sql>
			<file charset="utf8" driver="mysql">install.sql</file>
		</sql>
	</install>
	<uninstall>
		<sql>
			<file charset="utf8" driver="mysql">uninstall.sql</file>
		</sql>
	</uninstall>

	<administration>
		<!-- Administration Menu Section -->
		<menu>Development Tools</menu>
  
		<!-- Administration Main File Copy Section -->
		<files folder="admin">
			<filename>index.html</filename>
			<filename>admin.jdevtools.php</filename>
		</files>  
	</administration>
</install>

=== pasamio/pasamioprojects/migrationassistant/trunk/migrationassistant.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE install SYSTEM "http://dev.joomla.org/xml/1.5/component-install.dtd">
<install type="component" version="1.5.0">
 <name>Migration Assistant</name>
 <!-- The following elements are optional and free of formatting conttraints -->
 <creationDate>11-Feb-2008</creationDate>
 <author>Sam Moffatt</author>
 <authorEmail>pasamio@gmail.com</authorEmail>
 <authorUrl>http://sammoffatt.com.au</authorUrl>
 <copyright>Copyright (c) 2008 Toowoomba City Council/Sam Moffatt</copyright>
 <license>GNU GPL</license>
 <!--  The version string is recorded in the components table -->
 <version id="1">1.5</version>
 <!-- The description is optional and defaults to the name -->
 <description>This component copies across the values in the migration configuration table</description>
 <administration>
  <!-- Administration Menu Section -->
  <menu>Migration Assistant</menu>
  
  <!-- Administration Main File Copy Section -->
  <files folder="admin">
		<filename>admin.migrationassistant.php</filename>
		<filename>index.html</filename>
  </files>  
 </administration>
 <update>http://www.jsitepoint.com/update/components/migrationassistant</update>
</install>

=== pasamio/pasamioprojects/jpackageman/trunk/jpackageman.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE install SYSTEM "http://dev.joomla.org/xml/1.5/component-install.dtd">
<install type="component" version="1.5.0">
 <name>JPackageMan</name>
 <!-- The following elements are optional and free of formatting conttraints -->
 <creationDate>25-Oct-2007</creationDate>
 <author>Sam Moffatt</author>
 <authorEmail>sam.moffatt@toowoombarc.qld.gov.au</authorEmail>
 <authorUrl>http://www.toowoombarc.qld.gov.au</authorUrl>
 <copyright>Copyright (C) 2008 Toowoomba Regional Council/Sam Moffatt</copyright>
 <license>GNU GPL</license>
 <!--  The version string is recorded in the components table -->
 <version id="2">1.5.1</version>
 <!-- The description is optional and defaults to the name -->
 <description>This component is designed to allow bulk installation via packages</description>
 <installfile>install.php</installfile>
 <uninstallfile>uninstall.php</uninstallfile>
 <administration>
  <!-- Administration Menu Section -->
  <menu>Package Management</menu>
  
  <!-- Administration Main File Copy Section -->
  <files folder="admin">
		<!-- System Views, the default list and the detail screen --> 
		<filename>views/jpackageman/tmpl/default.php</filename>
		<filename>views/jpackageman/tmpl/index.html</filename>
		<filename>views/jpackageman/index.html</filename>
		<filename>views/jpackageman/view.html.php</filename>
		<filename>views/details/tmpl/index.html</filename>
		<filename>views/details/tmpl/default.php</filename>
		<filename>views/details/view.html.php</filename>
		<filename>views/index.html</filename>
		<!-- Data access models, default and details -->
		<filename>models/jpackageman.php</filename>
		<filename>models/index.html</filename>
		<filename>models/details.php</filename>
		<!-- Controller and Joomla! Admin landing point -->
		<filename>controller.php</filename>
		<filename>admin.jpackageman.php</filename>
		<filename>index.html</filename>
		<!-- Manifest for Joomla! 1.5 package -->
		<filename>manifests/joomla.xml</filename>
		<!-- The installer adapter to allow Joomla! 1.5 to handle packages -->
		<filename>include/package.php</filename>
		<filename>include/index.html</filename>
		<!-- jpackageman Support Class -->
		<filename>jpackageman.class.php</filename>
  </files>  
 </administration>
 <update>http://www.jsitepoint.com/update/components/jpackageman</update>
</install>

=== pasamio/pasamioprojects/advancedtools/joomla15/trunk/advancedtools.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE install SYSTEM "http://dev.joomla.org/xml/1.5/component-install.dtd">
<install type="component" version="1.5.0">
 <name>Advanced Tools</name>
 <!-- The following elements are optional and free of formatting conttraints -->
 <creationDate>25-Oct-2007</creationDate>
 <author>Sam Moffatt</author>
 <authorEmail>S.Moffatt@toowoomba.qld.gov.au</authorEmail>
 <authorUrl>http://www.toowoomba.qld.gov.au</authorUrl>
 <copyright>Copyright (c) 2007 Toowoomba City Council/Sam Moffatt</copyright>
 <license>GNU GPL</license>
 <!--  The version string is recorded in the components table -->
 <version id="1">1.0</version>
 <!-- The description is optional and defaults to the name -->
 <description>This component is designed to install the package and library installers as well as the advanced menu module</description>
 <installfile>install.php</installfile>
 <uninstallfile>uninstall.php</uninstallfile>
 <query>
 CREATE TABLE jos_advancedtools_menu (
menuid 	INT(11) AUTO_INCREMENT,
name 	VARCHAR(100) NOT NULL,
link	VARCHAR(255) NOT NULL,
class 	VARCHAR(50) NOT NULL,
csspath	VARCHAR(255) NOT NULL,
cssfile VARCHAR(20) NOT NULL,
published INT NOT NULL,
PRIMARY KEY (menuid)
);
 </query>
 <administration>
  <!-- Administration Menu Section -->
  <menu>Advanced Tools</menu>
  
  <!-- Administration Main File Copy Section -->
  <files folder="admin">
  		<!-- Packages -->
		<filename>packages/pkg_advtools.zip</filename>
		<filename>packages/com_jpackageman.zip</filename>
		<!-- System Views, the default list and the detail screen --> 
		<filename>views/advancedtools/tmpl/default.php</filename>
		<filename>views/advancedtools/tmpl/index.html</filename>
		<filename>views/advancedtools/index.html</filename>
		<filename>views/advancedtools/view.html.php</filename>
		<filename>views/details/tmpl/index.html</filename>
		<filename>views/details/tmpl/default.php</filename>
		<filename>views/details/view.html.php</filename>
		<filename>views/index.html</filename>
		<!-- Data access models, default and details -->
		<filename>models/advancedtools.php</filename>
		<filename>models/index.html</filename>
		<filename>models/details.php</filename>
		<!-- Controller and Joomla! Admin landing point -->
		<filename>controller.php</filename>
		<filename>admin.advancedtools.php</filename>
		<filename>index.html</filename>
  </files>  
 </administration>
 <update>http://www.jsitepoint.com/update/components/advancedtools</update>
</install>
